### ISSUE TITLE
Column with transformer option

### ISSUE THREAD

**Issue by unlight** [daniel7grant/eslint-plugin-typeorm-typescript#2]
https://orkhan.gitbook.io/typeorm/docs/entities#column-options

![](https://github.com/daniel7grant/eslint-plugin-typeorm-typescript/assets/301732/b67e951f-ec49-4e7f-94d1-17aa2ffdf5a6)

transformer (from, to) can transform text to anything, so rule should ignore type if decorator `@Column` has `transformer` options. Or better to forcing to type what `transformer.from` returns.

**Comment by daniel7grant** [comment]
Thank you for your issue. I added a new version (v0.2.5), which is supposed to fix this. Can you test it with your code?

**Comment by unlight** [comment]
Thanks. It works.
