### ISSUE TITLE
Quick Fix for type: 'date' adds code that does not compile

### ISSUE THREAD

**Issue by mprisehk** [daniel7grant/eslint-plugin-typeorm-typescript#6]
I have a Column with `type: 'date'` for which the Typescript type was `string | null`. The plugin shows an error for that:
![image](https://github.com/daniel7grant/eslint-plugin-typeorm-typescript/assets/149178064/949090b9-6fe0-4b1d-929d-4ffcf6aa2312)

It proposes a Quick Fix:
![image](https://github.com/daniel7grant/eslint-plugin-typeorm-typescript/assets/149178064/1d4da89c-e54a-4440-b9be-7fca01b2bb02)

However, the Quick Fix adds an unknown type of 'date'. So after the fix, the code no longer compiles:
![image](https://github.com/daniel7grant/eslint-plugin-typeorm-typescript/assets/149178064/e414edd0-c35f-494a-a1ac-25789616c824)

This seems unintentional. Is it supposed to be adding the Javascript type `Date` (not sure if TypeORM supports that)? Or does it simply map to a `string`?
Both options are accepted by the plugin:
![image](https://github.com/daniel7grant/eslint-plugin-typeorm-typescript/assets/149178064/07f07707-e448-43ce-924d-188afdd996d2)
But in any case, the option added by the Quick Fix is incorrect.

**Comment by daniel7grant** [comment]
You are correct, it had all the types lowercased. I fixed it, so it is matching with the TypeScript types. It will be out in the next minor release.

**Comment by mprisehk** [comment]
Tested & it works swimmingly 😄 Thanks!
